"""Generate the standalone service contract from its canonical core owners."""

import argparse
import ast
from pathlib import Path


def generated_contract(repository: Path) -> str:
    retrievers = repository / "ragent_core/ragent_core/retrievers"
    contract = (retrievers / "model_contract.py").read_text(encoding="utf-8")
    settings = (retrievers / "settings.py").read_text(encoding="utf-8")
    names = {"DEFAULT_EMBEDDING_MODEL_NAME", "DEFAULT_RERANKER_MODEL_NAME"}
    defaults = [
        ast.get_source_segment(settings, node)
        for node in ast.parse(settings).body
        if isinstance(node, ast.Assign)
        and any(
            isinstance(target, ast.Name) and target.id in names
            for target in node.targets
        )
    ]
    if len(defaults) != len(names):
        raise ValueError("Canonical model defaults are missing or ambiguous")
    tree = ast.parse(contract)
    body = contract.splitlines(keepends=True)
    insertion = next(
        node.lineno - 1 for node in tree.body if isinstance(node, ast.ClassDef)
    )
    body[insertion:insertion] = ["\n".join(defaults) + "\n\n\n"]
    header_end = tree.body[0].end_lineno if ast.get_docstring(tree) else 0
    return (
        '"""Generated by scripts/sync_model_contract.py; do not edit by hand."""\n'
        + "".join(body[header_end:])
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the generated file is stale"
    )
    args = parser.parse_args()
    repository = Path(__file__).resolve().parents[2]
    destination = repository / "model_services/model_services/model_contract.py"
    expected = generated_contract(repository)
    if args.check:
        if destination.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "Model contract is stale; run scripts/sync_model_contract.py"
            )
    else:
        destination.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
