import math
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class FinalizePaths:
    directory: Path
    raw_directory: Path
    entity_facts: Path
    qas: Path
    failures: Path
    metadata: Path
    lock: Path


@dataclass(frozen=True)
class EntityQASummary:
    entity_name: str
    requested: int
    generated: int
    crashed: bool = False
    error: str | None = None
    phoenix_trace_id: str = ""


@dataclass
class QA:
    """Atomic QA pair generated by the default pipeline. This follows the verifiers format of question, answer and info (info is a dict for metadata)"""

    question: str
    answer: str
    doc_ids: list[int] = field(default_factory=list)
    info: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "question": self.question,
            "answer": self.answer,
            "doc_ids": self.doc_ids,
            "info": self.info,
        }


class ComplexityLevel(StrEnum):
    SIMPLE = "simple"
    COMPLEX = "complex"


@dataclass(kw_only=True)
class GeneratedQA(QA):
    complexity: ComplexityLevel

    def to_dict(self) -> dict[str, Any]:
        return {
            **super().to_dict(),
            "info": {**self.info, "complexity": self.complexity.value},
        }


@dataclass
class ComplexityQuota:
    target: int
    required_complex: int
    accepted: list[GeneratedQA] = field(default_factory=list)

    @classmethod
    def from_ratio(cls, target: int, ratio: float) -> "ComplexityQuota":
        return cls(target, min(target, math.ceil(target * ratio)))

    @property
    def remaining_slots(self) -> int:
        return self.target - len(self.accepted)

    @property
    def remaining_complex(self) -> int:
        count = sum(qa.complexity is ComplexityLevel.COMPLEX for qa in self.accepted)
        return max(0, self.required_complex - count)

    def generation_targets(self) -> list[bool]:
        complex_count = min(self.remaining_complex, self.remaining_slots)
        return [True] * complex_count + [False] * (self.remaining_slots - complex_count)

    def can_accept(self, candidate: GeneratedQA) -> bool:
        return self.remaining_slots > 0 and (
            candidate.complexity is ComplexityLevel.COMPLEX
            or self.remaining_slots > self.remaining_complex
        )
